name: Java CI with Gradle

on:
  push:
    branches:
      - '**'
    paths:
      - 'inventory-microservice/**'
      - 'order-microservice/**'
      - 'payment-microservice/**'
      - 'kafka-lib/**'
      - 'shared-kernel/**'
      - 'shared-test/**'
      - 'build.gradle'
      - 'settings.gradle'
      - 'gradle.properties'
      - 'gradle/**'
      - 'gradlew'
      - 'gradlew.bat'
      - '.github/workflows/gradle.yml'
      - '.github/workflows/test-coverage.yml'
  pull_request:
    branches:
      - '**'
    paths:
      - 'inventory-microservice/**'
      - 'order-microservice/**'
      - 'payment-microservice/**'
      - 'kafka-lib/**'
      - 'shared-kernel/**'
      - 'shared-test/**'
      - 'build.gradle'
      - 'settings.gradle'
      - 'gradle.properties'
      - 'gradle/**'
      - 'gradlew'
      - 'gradlew.bat'
      - '.github/workflows/gradle.yml'
      - '.github/workflows/test-coverage.yml'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK 21
        uses: actions/setup-java@v4.7.1
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Publish the libraries to maven
        run: ./gradlew publishToMavenLocal --no-configuration-cache
      - name: Build microservices and run tests with Gradle
        run: |          
          ./gradlew build
